In [1]:
import numpy as np
np.random.seed(42)

In [2]:
array = np.random.randint(0, 100, size=(10, 3))

In [3]:
print(f'the size is {array.shape}\nthe array is \n{array}')

the size is (10, 3)
the array is 
[[51 92 14]
 [71 60 20]
 [82 86 74]
 [74 87 99]
 [23  2 21]
 [52  1 87]
 [29 37  1]
 [63 59 20]
 [32 75 57]
 [21 88 48]]
